apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- octopub-products.yaml

configMapGenerator:
  - name: product-service-env-vars
    env: variables.properties

generatorOptions:
  disableNameSuffixHash: true
